version: "3.8"

services:
  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: task_scheduler
    ports:
      - "3307:3306"

  scheduler:
    build:
      context: ./scheduler
    ports:
      - "5000:5000"
    depends_on:
      - mysql
      - rabbitmq
    environment:
      DATABASE_URL: "mysql+mysqlconnector://root:password@mysql:3306/task_scheduler"
      RABBITMQ_HOST: rabbitmq

  worker:
    build:
      context: ./workers
    depends_on:
      - rabbitmq
      - mysql
    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: password
      RABBITMQ_HOST: rabbitmq
