name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: task_scheduler
        ports:
          - "3306:3306"

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Install Dependencies
        run: |
          cd scheduler
          pip install -r requirements.txt

      - name: Run Python Tests
        run: |
          cd scheduler
          pytest

      - name: Compile Java Workers
        run: |
          cd workers
          javac -cp libs/*:src/main/java -d out src/main/java/com/taskworker/Worker.java
